name: "Run Tests"

on:
  pull_request:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            dependencies-php-${{ matrix.php }}-composer-

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype, curl, date, dom, fileinfo, filter, gd, hash, iconv, intl, json, libxml, mbstring, openssl, pcntl, pcre, pdo, pdo_sqlite, phar, posix, simplexml, spl, sqlite, tokenizer, tidy, xml, xmlreader, xmlwriter, zip, zlib
          coverage: pcov

      - name: Prepare Laravel Application
        run: cp .env.example .env

      - name: Install PHP dependencies (composer)
        run: composer install --no-interaction --no-suggest

      - name: Execute PHP tests
        run: composer test
